### ISSUE TITLE
Candidate password reset not working

### ISSUE THREAD

**Issue by AngelaCRS** [lanternbox/exploreCRS#26] opened 2017-01-11 10:34 UTC
Hi,

One of my candidate's Ilona Gruchot tried resetting her password today but wasn't able to as the reset link is taking her to an error page. We also tested it with Robin's test candidate account and he got an email to reset his password but the link took him to the same error page. Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/23715436/21845178/92ac6d48-d82c-11e6-9d58-36c94849de7a.png)

**Comment by lantern-andrew** [comment] 2017-01-11 12:22
Hi Angela, sorry for the trouble and thanks for pointing that out. We found and fixed a bug related to how the password tokens were generated. It was caused by yesterday's upload and would have affected anyone who made a password request. It's fixed now (tested for candidates and schools).

**Closed by lantern-andrew** 2017-01-11 12:22 UTC
